### ISSUE TITLE
Can't show more than about 10-15 layers without hitting the gmaps url limit

### ISSUE THREAD

**Issue by njakobsen** [culturecode/maps_engine#6]
Maybe we can merge editable layers when sending out the query. The query could be, "give me layers 1,2,3,5,77,100" and the server would respond with kml showing the features from those layers

**Comment by rywall** [comment]
Or it might be best to just render the FeatureLayers on the client side (like we do on the edit page) instead of sending out for KML.

**Comment by rywall** [comment]
Fixed.
